[package]
name = "bento-examples"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bento = { path = "../bento" }
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
serde_json = "1.0"
chrono = "0.4"